#!/bin/bash -x

xterm -e 'socat TCP-LISTEN:6001,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"' &
SOCAT=$!

docker run --rm \
  --net=host \
  --cap-add SYS_ADMIN \
  --device /dev/fuse \
  --privileged \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $PWD:$PWD \
  -w $PWD \
  -e WORKDIR=$PWD \
  -v $HOME/.ssh:/root/.ssh \
  -v $HOME/.gitconfig:/root/.gitconfig \
  -v $HOME/.kube:/root/.kube \
  -v $HOME/.docker:/root/.docker \
  -v $HOME/.config/gcloud:/root/.config/gcloud \
  -v $HOME/.m2:/root/.m2 \
  -v $HOME/.ivy2:/root/.ivy2 \
  -v $HOME/.coursier:/root/.coursier \
  -v $HOME/.cache:/root/.cache \
  -e DISPLAY=$(ifconfig en0 | grep "inet " | cut -d " " -f 2):1 \
  -e XAUTHORITY=/tmp/xauth \
  -P \
  -it natb1/dotfiles $@

kill $SOCAT
